#global config
global:
  scrape_interval: 15s
  evaluation_interval: 5s
  scrape_timeout: 2s
  external_labels:
    monitor: 'csvserver-monitor'
# Scrape configs only contain one scrape target
scrape_configs:
  - job_name: 'csvserver'
    # Override the global default and scrape targets from this job every 5 seconds.
    scrape_interval: 5s
    static_configs:
      - targets: ['csvserver:9300']
